2025-06-16 12:25:22,532 - root - INFO - Supabase URL: https://rawkkzxzkiuauuxrjxtd.supabase.co
2025-06-16 12:25:22,532 - root - INFO - 데이터베이스 파일 위치: C:\Users\dohwa\Desktop\MyPlugin\posprinter_supabase\cache.db
2025-06-16 12:25:22,664 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): rawkkzxzkiuauuxrjxtd.supabase.co:443
2025-06-16 12:25:23,566 - urllib3.connectionpool - DEBUG - https://rawkkzxzkiuauuxrjxtd.supabase.co:443 "GET /rest/v1/order?select=%2A HTTP/1.1" 200 None
2025-06-16 12:25:23,575 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): rawkkzxzkiuauuxrjxtd.supabase.co:443
2025-06-16 12:25:23,667 - urllib3.connectionpool - DEBUG - https://rawkkzxzkiuauuxrjxtd.supabase.co:443 "GET /rest/v1/order_item?select=%2A HTTP/1.1" 200 None
2025-06-16 12:25:23,675 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): rawkkzxzkiuauuxrjxtd.supabase.co:443
2025-06-16 12:25:23,764 - urllib3.connectionpool - DEBUG - https://rawkkzxzkiuauuxrjxtd.supabase.co:443 "GET /rest/v1/order_item_option?select=%2A HTTP/1.1" 200 None
2025-06-16 12:25:24,144 - root - INFO - 프로그램이 성공적으로 시작되었습니다.
2025-06-16 12:25:27,438 - src.printer.manager - ERROR - 프린터 오류: (1801, 'OpenPrinter', '프린터 이름이 올바르지 않습니다.')
Traceback (most recent call last):
  File "C:\Users\dohwa\Desktop\MyPlugin\posprinter_supabase\src\printer\manager.py", line 81, in print_receipt
    handle = win32print.OpenPrinter(self.printer_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pywintypes.error: (1801, 'OpenPrinter', '프린터 이름이 올바르지 않습니다.')
2025-06-16 12:25:27,669 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): rawkkzxzkiuauuxrjxtd.supabase.co:443
2025-06-16 12:25:27,769 - urllib3.connectionpool - DEBUG - https://rawkkzxzkiuauuxrjxtd.supabase.co:443 "GET /rest/v1/order?select=order_id&order=order_id.desc&limit=1 HTTP/1.1" 200 None
2025-06-16 12:29:35,706 - root - INFO - Supabase URL: https://rawkkzxzkiuauuxrjxtd.supabase.co
2025-06-16 12:29:35,707 - root - INFO - 데이터베이스 파일 위치: C:\Users\dohwa\Desktop\MyPlugin\posprinter_supabase\cache.db
2025-06-16 12:29:35,771 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): rawkkzxzkiuauuxrjxtd.supabase.co:443
2025-06-16 12:29:36,268 - urllib3.connectionpool - DEBUG - https://rawkkzxzkiuauuxrjxtd.supabase.co:443 "GET /rest/v1/order?select=%2A HTTP/1.1" 200 None
2025-06-16 12:29:36,279 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): rawkkzxzkiuauuxrjxtd.supabase.co:443
2025-06-16 12:29:36,324 - urllib3.connectionpool - DEBUG - https://rawkkzxzkiuauuxrjxtd.supabase.co:443 "GET /rest/v1/order_item?select=%2A HTTP/1.1" 200 None
2025-06-16 12:29:36,333 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): rawkkzxzkiuauuxrjxtd.supabase.co:443
2025-06-16 12:29:36,393 - urllib3.connectionpool - DEBUG - https://rawkkzxzkiuauuxrjxtd.supabase.co:443 "GET /rest/v1/order_item_option?select=%2A HTTP/1.1" 200 None
2025-06-16 12:29:36,750 - root - INFO - 프로그램이 성공적으로 시작되었습니다.
2025-06-16 12:29:39,366 - src.printer.manager - ERROR - 프린터 오류: [Errno 2] No such file or directory: '/scr/printer/test_print_output.txt'
Traceback (most recent call last):
  File "C:\Users\dohwa\Desktop\MyPlugin\posprinter_supabase\src\printer\manager.py", line 102, in print_receipt
    p = File("/scr/printer/test_print_output.txt")  # 또는 "test_receipt.bin" (Windows에서는 "C:\\temp\\test_receipt.bin")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dohwa\Desktop\MyPlugin\posprinter_supabase\venv\Lib\site-packages\escpos\printer.py", line 271, in __init__
    self.open()
  File "C:\Users\dohwa\Desktop\MyPlugin\posprinter_supabase\venv\Lib\site-packages\escpos\printer.py", line 275, in open
    self.device = open(self.devfile, "wb")
                  ^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/scr/printer/test_print_output.txt'
2025-06-16 12:29:40,765 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): rawkkzxzkiuauuxrjxtd.supabase.co:443
2025-06-16 12:29:40,846 - urllib3.connectionpool - DEBUG - https://rawkkzxzkiuauuxrjxtd.supabase.co:443 "GET /rest/v1/order?select=order_id&order=order_id.desc&limit=1 HTTP/1.1" 200 None
2025-06-16 12:29:54,063 - root - INFO - Supabase URL: https://rawkkzxzkiuauuxrjxtd.supabase.co
2025-06-16 12:29:54,064 - root - INFO - 데이터베이스 파일 위치: C:\Users\dohwa\Desktop\MyPlugin\posprinter_supabase\cache.db
2025-06-16 12:29:54,130 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): rawkkzxzkiuauuxrjxtd.supabase.co:443
2025-06-16 12:29:54,200 - urllib3.connectionpool - DEBUG - https://rawkkzxzkiuauuxrjxtd.supabase.co:443 "GET /rest/v1/order?select=%2A HTTP/1.1" 200 None
2025-06-16 12:29:54,218 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): rawkkzxzkiuauuxrjxtd.supabase.co:443
2025-06-16 12:29:54,267 - urllib3.connectionpool - DEBUG - https://rawkkzxzkiuauuxrjxtd.supabase.co:443 "GET /rest/v1/order_item?select=%2A HTTP/1.1" 200 None
2025-06-16 12:29:54,275 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): rawkkzxzkiuauuxrjxtd.supabase.co:443
2025-06-16 12:29:54,358 - urllib3.connectionpool - DEBUG - https://rawkkzxzkiuauuxrjxtd.supabase.co:443 "GET /rest/v1/order_item_option?select=%2A HTTP/1.1" 200 None
2025-06-16 12:29:54,738 - root - INFO - 프로그램이 성공적으로 시작되었습니다.
2025-06-16 12:29:56,531 - src.printer.manager - ERROR - 프린터 오류: [Errno 13] Permission denied: '/test_print_output.txt'
Traceback (most recent call last):
  File "C:\Users\dohwa\Desktop\MyPlugin\posprinter_supabase\src\printer\manager.py", line 102, in print_receipt
    p = File("/test_print_output.txt")  # 또는 "test_receipt.bin" (Windows에서는 "C:\\temp\\test_receipt.bin")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dohwa\Desktop\MyPlugin\posprinter_supabase\venv\Lib\site-packages\escpos\printer.py", line 271, in __init__
    self.open()
  File "C:\Users\dohwa\Desktop\MyPlugin\posprinter_supabase\venv\Lib\site-packages\escpos\printer.py", line 275, in open
    self.device = open(self.devfile, "wb")
                  ^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/test_print_output.txt'
